// swift-tools-version:5.9
import PackageDescription

// NOTE: generated by Scripts/generate_project.py — edit that script (or mirror the change there).
//
// PianoMonitorKit is verified against macOS 10.15 by `swift test`, which is what keeps the
// Catalina promise honest. The macOS/iOS UI layers and the app bundles are built by Xcode at
// macOS 14 / iOS 17 because they use SwiftUI APIs that do not exist on 10.15.

let package = Package(
    name: "PianoMonitor",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v17),
    ],
    products: [
        .library(name: "PianoMonitorKit", targets: ["PianoMonitorKit"]),
        .executable(name: "PianoMonitorAnalyzer", targets: ["PianoMonitorAnalyzer"]),
    ],
    targets: [
        // One target, guarded internally with `#if PIANOMONITOR_MAC`. The shared third — models,
        // settings, API contracts, JSON store — is compiled for iOS too; the audio, analysis and
        // detection layers are macOS-only because they depend on CoreAudio/Accelerate types that do
        // not exist on iOS, and because the iOS app is deliberately a pure viewer.
        .target(name: "PianoMonitorKit", path: "Sources/PianoMonitorKit"),
        .testTarget(
            name: "PianoMonitorKitTests",
            dependencies: ["PianoMonitorKit"],
            path: "Tests/PianoMonitorKitTests"
        ),
        // Hardware bench: runs the production detector against live input. Needs macOS 14 for the
        // SwiftData store, so it is an executable rather than part of the Kit.
        .executableTarget(
            name: "PianoMonitorAnalyzer",
            dependencies: ["PianoMonitorKit"],
            path: "Sources/PianoMonitorAnalyzer"
        ),
    ]
)
